In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
arr1 = np.array([432,542,542,674,542,653,18, 8])

print(arr1)

[432 542 542 674 542 653  18   8]


In [3]:
type(arr1)

numpy.ndarray

In [4]:
arr_2d =  np.array([[1,23,54], [4328,543,43]])
print(arr_2d.ndim)

2


In [5]:
arr1.ndim

1

In [6]:
arr1.shape

(8,)

In [7]:
arr1.size

8

In [8]:
arr_2d.size

6

In [9]:
arr_2d.shape

(2, 3)

In [10]:
arr_2d.dtype

dtype('int64')

In [11]:
ones = np.ones(5)
ones

array([1., 1., 1., 1., 1.])

In [12]:
ones.dtype

dtype('float64')

In [13]:
np.ones((4,4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [14]:
np.zeros((4,4), dtype=float)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((3,3), dtype=bool)

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [16]:
np.zeros((3,3), dtype=str)

array([['', '', ''],
       ['', '', ''],
       ['', '', '']], dtype='<U1')

In [17]:
np.ones((3,3), dtype=str)

array([['1', '1', '1'],
       ['1', '1', '1'],
       ['1', '1', '1']], dtype='<U1')

In [18]:
np.empty((4,5))

array([[0. , 0. , 0.3, 1. , 0. ],
       [0. , 1. , 1. , 1. , 1. ],
       [1. , 1. , 1. , 0. , 0. ],
       [1. , 0.5, 0. , 0. , 1. ]])

In [19]:
np.empty(5, dtype=int)

array([4607182418800017408, 4607182418800017408, 4607182418800017408,
       4607182418800017408, 4607182418800017408])

In [20]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [21]:
np.linspace(1,100, 5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [22]:
arr_2d.reshape(1, 6)

array([[   1,   23,   54, 4328,  543,   43]])

In [ ]:
arr1.reshape(4,2)

In [ ]:
x = np.arange(1,13).reshape((2,3,2))

In [ ]:
x.ravel()

In [ ]:
x.flatten()

In [ ]:
x.transpose()

In [ ]:
m1 = np.arange(1,10).reshape((3,3))
m1

In [ ]:
m2 = np.arange(11,20).reshape((3,3))
m2

In [ ]:
np.add(m1,m2)

In [ ]:
np.subtract(m2, m1)

In [ ]:
np.divide(m2, m1)

In [ ]:
np.multiply(m1, m2)

In [ ]:
m1 @ m2

In [ ]:
np.dot(m1, m2)

In [ ]:
int(np.dot(m1, m2).max())

In [ ]:
np.dot(m1, m2).argmax()

In [ ]:
np.dot(m1, m2).max(axis=1)

In [ ]:
np.dot(m1, m2).min(axis=0)

In [ ]:
np.dot(m1, m2).sum()

In [ ]:
np.sum(m1, axis=1)

In [ ]:
np.mean(m1)

In [ ]:
np.sqrt(m1)

In [ ]:
np.std(m1)

In [ ]:
np.exp(m1)

In [ ]:
np.log(m1)

In [ ]:
np.log10(m1)

In [ ]:
m3 = np.arange(1,101).reshape(10,10)
m3

In [ ]:
m3[3:5,3:5]

In [ ]:
m3[:, 4]

In [ ]:
np.concatenate((m1, m2))

In [ ]:
np.concatenate((m1, m2), axis=1)

In [ ]:
np.hstack((m1, m2))

In [ ]:
np.vstack((m1, m2))

In [ ]:
np.split(m1, 3)

In [ ]:
np.split(m1, 3, axis=1)

In [ ]:
np.split(m1, [1,3])

In [ ]:
np.sin(30)

In [ ]:
np.cos(180)

In [ ]:
np.tan(90)

In [ ]:
sin_x = np.arange(0, 3*np.pi, 0.1)
sin_x

In [ ]:
sin_y = np.sin(sin_x)

In [ ]:
sin_y

In [ ]:
plt.plot(sin_x, sin_y)
plt.show()

In [ ]:
cos_y = np.cos(sin_x)
plt.plot(sin_x, cos_y)
plt.show()

In [ ]:
tan_y = np.tan(sin_x)
plt.plot(sin_x, tan_y)
plt.show()

In [ ]:
np.sin(30 * np.pi / 180)

In [ ]:
np.random.random(5)

In [ ]:
np.random.randint(1,4)

In [ ]:
np.random.randint(1, 4, (3,6))

In [ ]:
np.random.seed(5)

In [ ]:
np.random.randint(1, 4, (3,6))

In [ ]:
np.random.seed(5)
np.random.randint(1, 4, (3,6))

In [ ]:
np.random.rand(5)

In [ ]:
np.random.randn(3,3)

In [ ]:
np.random.choice(np.random.randn(3))

In [ ]:
np.random.permutation(np.random.randn(3,3))

In [24]:
ch_name = "This is a sampletest text"
another = "This is another testtext"
np.char.add(ch_name, another)

np.str_('This is a sampletest textThis is another testtext')

In [25]:
np.char.upper(ch_name)

array('THIS IS A SAMPLETEST TEXT', dtype='<U25')

In [26]:
np.char.lower(ch_name)

array('this is a sampletest text', dtype='<U25')

In [29]:
np.char.center(ch_name, 50, fillchar='*')

array('************This is a sampletest text*************', dtype='<U50')

In [33]:
np.char.split(ch_name)

array(list(['This', 'is', 'a', 'sampletest', 'text']), dtype=object)

In [34]:
np.char.splitlines("abcd\ndef")

array(list(['abcd', 'def']), dtype=object)

In [35]:
np.char.replace(ch_name, 'text', 'ion')

array('This is a sampletest ion', dtype='<U24')

In [37]:
np.char.equal("", "")

array(True)

In [38]:
np.char.count("a", 'a')

np.int64(1)

In [40]:
np.char.find(ch_name, 'text')

NameError: name 'char_name' is not defined